# Sparse matrix storage

In [18]:
import numpy as np

np.array([
    [1.0, 2.0, 0.0, 0.0, 5.0],
    [0.0, 0.0, -3.0, 4.0, 0.0],
    [0.0, -2.0, 0.0, 0.0, -5.0],
    [-1.0, 0.0, 0.0, -4.0, 0.0],
    [0.0, 3.0, 0.0, 0.0, 6.0]])

array([[ 1.,  2.,  0.,  0.,  5.],
       [ 0.,  0., -3.,  4.,  0.],
       [ 0., -2.,  0.,  0., -5.],
       [-1.,  0.,  0., -4.,  0.],
       [ 0.,  3.,  0.,  0.,  6.]])

# Coordinate format (COO)
Using *0-based* indices

In [21]:
row_idx = [3, 4, 0, 0, 4, 1, 3, 2, 2, 1, 0]
col_idx = [0, 1, 1, 0, 4, 2, 3, 4, 1, 3, 4]
val = [-1.0, 3.0, 2.0, 1.0, 6.0, -3.0, -4.0, -5.0, -2.0, 4.0, 5.0]

In [22]:
from scipy.sparse import coo_matrix
coo_matrix((val,(row_idx, col_idx))).toarray()

array([[ 1.,  2.,  0.,  0.,  5.],
       [ 0.,  0., -3.,  4.,  0.],
       [ 0., -2.,  0.,  0., -5.],
       [-1.,  0.,  0., -4.,  0.],
       [ 0.,  3.,  0.,  0.,  6.]])

# Compressed Sparse Column (CSC)

In [66]:
row_idx = [0, 3, 0, 2, 4, 1, 1, 4, 0, 2, 4]
col_ptr = [0, 2, 5, 6, 8, 11]
val = [1.0, -1.0, 2.0, -2.0, 3.0, -3.0, 4.0, -4.0, 5.0, -5.0, 6.0]

In [67]:
from scipy.sparse import csc_matrix
csc_matrix((val,row_idx, col_ptr)).toarray()

array([[ 1.,  2.,  0.,  0.,  5.],
       [ 0.,  0., -3.,  4.,  0.],
       [ 0., -2.,  0.,  0., -5.],
       [-1.,  0.,  0.,  0.,  0.],
       [ 0.,  3.,  0., -4.,  6.]])

# Compressed Sparse Row (CSR)

In [68]:
col_idx = [0, 1, 4, 2, 3, 1, 4, 0, 1, 3, 4]
row_ptr = [0, 3, 5, 7, 8, 11]
val = [1.0, 2.0, 5.0, -3.0, 4.0, -2.0, -5.0, -1.0, 3.0, -4.0, 6.0]

In [70]:
from scipy.sparse import csr_matrix
csr_matrix((val,col_idx, row_ptr)).toarray()

array([[ 1.,  2.,  0.,  0.,  5.],
       [ 0.,  0., -3.,  4.,  0.],
       [ 0., -2.,  0.,  0., -5.],
       [-1.,  0.,  0.,  0.,  0.],
       [ 0.,  3.,  0., -4.,  6.]])