# Sparse matrix storage

In [6]:
import numpy as np

a = np.array([
    [1.0, 2.0, 0.0, 0.0, 5.0],
    [0.0, 0.0, -3.0, 4.0, 0.0],
    [0.0, -2.0, 0.0, 0.0, -5.0],
    [-1.0, 0.0, 0.0, -4.0, 0.0],
    [0.0, 3.0, 0.0, 0.0, 6.0]])

print a

[[ 1.  2.  0.  0.  5.]
 [ 0.  0. -3.  4.  0.]
 [ 0. -2.  0.  0. -5.]
 [-1.  0.  0. -4.  0.]
 [ 0.  3.  0.  0.  6.]]


# Coordinate format (COO)

# Compressed Sparse Column (CSC)