# Sparse matrix storage

In [15]:
import numpy as np

a = np.array([
    [1.0, 2.0, 0.0, 0.0, 5.0],
    [0.0, 0.0, -3.0, 4.0, 0.0],
    [0.0, -2.0, 0.0, 0.0, -5.0],
    [-1.0, 0.0, 0.0, -4.0, 0.0],
    [0.0, 3.0, 0.0, 0.0, 6.0]])

print a

[[ 1.  2.  0.  0.  5.]
 [ 0.  0. -3.  4.  0.]
 [ 0. -2.  0.  0. -5.]
 [-1.  0.  0. -4.  0.]
 [ 0.  3.  0.  0.  6.]]


# Coordinate format (COO)
Using *0-based* indices

In [12]:
row_index = [3, 4, 0, 0, 4, 1, 3, 2, 2, 1, 0]
col_index = [0, 1, 1, 0, 4, 2, 3, 4, 1, 3, 4]
val = [-1.0, 3.0, 2.0, 1.0, 6.0, -3.0, -4.0, -5.0, -2.0, 4.0, 5.0]

In [16]:
from scipy.sparse import coo_matrix
a_coo_matrix((val,(row_index, col_index))).toarray()

# Compressed Sparse Column (CSC)